export const phrases: string[] = [
  "Innovate. Inspire. Ignite.",
  "Our passion drives progress.",
  "Think outside the bot.",
  "Limitless possibilities await.",
  "Building bots, building futures.",
  "Create. Innovate. Dominate.",
  "Fueled by determination and innovation.",
  "Machines with a mission.",
  "Boldly going where no bot has gone before.",
  "We build. We code. We compete.",
  "Leave no screw unturned.",
  "Success is built one bot at a time.",
  "We bring the bots to life.",
  "Robotics: The ultimate team sport.",
  "The future is now.",
  "We build robots and so much more.",
  "Driven by excellence and innovation.",
  "Innovate. Build. Repeat.",
  "We build the future, one bot at a time.",
  "The power of robotics, the power of us.",
  "Innovation never sleeps.",
  "Pushing the boundaries of possibility.",
  "Building a better world, one bot at a time.",
  "Robotics: Where creativity meets engineering.",
  "Working hard, playing hard, building robots.",
  "Making the impossible, possible.",
  "Aim high, build higher.",
  "The only limit is the one you set.",
  "We don't just build robots, we build leaders.",
  "Engineering the future.",
  "Building bots, building character.",
  "Dream it. Build it. Compete.",
  "Building bots, changing lives.",
  "Together, we can change the world.",
  "Creating a future without limits.",
  "Building more than just robots.",
  "The spark of innovation ignites the future.",
  "Our passion fuels our success.",
  "Where robotics meets imagination.",
  "Building a brighter future, one bot at a time.",
  "When innovation meets determination, anything is possible.",
  "The power of collaboration and innovation.",
  "Building a better tomorrow, today.",
  "Empowering the next generation of innovators.",
  "Building bots, building community.",
  "We build more than just robots, we build friendships.",
  "The future is in our hands.",
  "Let's create something amazing together.",
  "Building bots, building connections.",
  "Design. Build. Inspire.",
  "Where imagination meets reality.",
  "Designing a better world, one robot at a time.",
  "Building bots, building dreams.",
  "Let's change the world together.",
  "Where science, technology, and imagination meet.",
  "Building robots, building the future.",
  "Innovation, passion, and teamwork.",
  "Design. Build. Compete.",
  "Robots that rock.",
  "The power of engineering.",
  "Building robots, building better futures.",
  "Designing a brighter future.",
  "Where robots meet reality.",
  "Building bots, building a better world.",
  "Innovation at its finest.",
  "Building the future, one bot at a time.",
  "Where engineering meets creativity.",
  "Innovation in action.",
  "Designing the future today.",
  "Building bots, building success.",
  "Dream it. Build it. Change the world.",
  "Innovation without boundaries.",
  "Building bots, building better people.",
  "Pushing the limits of innovation.",
  "Designing a world of possibilities.",
  "Engineering the impossible.",
  "Building bots, changing the game.",
  "Unleashing the power of innovation.",
  "Designing a world of change.",
];
