import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/6070-logo.png" />

        <link rel="preload" href="/season/6070-charged-up.png" as="image" />
        <link rel="preload" href="/season/6070-power-up.png" as="image" />
        <link rel="preload" href="/season/6070-destination-deep-space.jpg" as="image" />
        <link rel="preload" href="/season/6070-steamworks.jpg" as="image" />
        <link rel="preload" href="/season/6070-stronghold.jpg" as="image" />

      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
