import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>6070: Gryphon Machine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/6070-logo.png" />
      </Head>
      <Navbar />
      <div
        className={`px-7 mt-20 py-[50px] rounded-lg flex flex-col md:flex-row items-center justify-center mb-5`}
      >
        <div className="mt-20 md:m-0">
          <Image
            className="py-2 pr-4 ml-8 mt-0"
            src="/6070-logo.png"
            alt="6070 Logo"
            width={100}
            height={100}
            priority={true}
          />
        </div>
        <div className="flex flex-col px-4">
          <div className="mb-3">
            <p className="text-center text-5xl md:text-4xl font-bold text-primary">
              Gryphon Machine
            </p>
            <span className="text-left md:text-xl text-secondary">
              A{" "}
              <span className="underline">
                <a
                  href="https://www.firstinspires.org/robotics/frc"
                  target="_blank"
                >
                  FIRST
                </a>
              </span>{" "}
              Robotics Team
            </span>
          </div>
        </div>
      </div>{" "}
      <Footer />
    </>
  );
}
